server:
  port: 9006
spring:
#  h2:
#    console:
#      enabled: true
#      path: /console
  datasource:
    url: jdbc:h2:mem:spring_security
    username: sa
    password:
    driverClassName: org.h2.Driver
